services:
  mysql:
    image: mysql:8.0.35
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 091022    
      MYSQL_USER: admin              
      MYSQL_PASSWORD: 091022admin      
      MYSQL_DATABASE: books_ms       
    ports:
      - "3306:3306"                  
    volumes:
      - mysql_data:/var/lib/mysql    
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - books_network  

  nestjs-app:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: nestjs_container
    environment:
      DATABASE_URL: "mysql://admin:091022admin@mysql:3306/books_ms"
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - books_network  

volumes:
  mysql_data:

networks:
  books_network:
    driver: bridge
    name: books_network